#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

declare -a bs=("Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School")

for val in "${bs[@]}"; do
echo "$val"
done  
